// This is an automatically generated file. Please do not edit this file directly.
'use server';

/**
 * @fileOverview A translation AI agent that translates assessment output to the user's language.
 *
 * - translateAssessment - A function that handles the translation process.
 * - TranslateAssessmentInput - The input type for the translateAssessment function.
 * - TranslateAssessmentOutput - The return type for the translateAssessment function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TranslateAssessmentInputSchema = z.object({
  text: z.string().describe('The text to translate.'),
  language: z.enum(['en', 'fr', 'ar']).describe('The target language code (en, fr, ar).'),
});
export type TranslateAssessmentInput = z.infer<typeof TranslateAssessmentInputSchema>;

const TranslateAssessmentOutputSchema = z.object({
  translatedText: z.string().describe('The translated text.'),
});
export type TranslateAssessmentOutput = z.infer<typeof TranslateAssessmentOutputSchema>;

export async function translateAssessment(input: TranslateAssessmentInput): Promise<TranslateAssessmentOutput> {
  return translateAssessmentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'translateAssessmentPrompt',
  input: {schema: TranslateAssessmentInputSchema},
  output: {schema: TranslateAssessmentOutputSchema},
  prompt: `Translate the following text to {{language}}:

{{{text}}}`, 
});

const translateAssessmentFlow = ai.defineFlow(
  {
    name: 'translateAssessmentFlow',
    inputSchema: TranslateAssessmentInputSchema,
    outputSchema: TranslateAssessmentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
